### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by qkdrk7777775** [coolbutuseless/ggpattern#77] opened 2022-04-19 11:15 UTC
**I tried running the example, but it did not work properly because the following error occurred in the Windows operating system.**

[example](https://coolbutuseless.github.io/package/ggpattern/articles/geom-gallery-array.html#geom-bar-pattern-coord-flip-and-fit-image-to-height-and-graivty-towards-the-east-)

![image](https://user-images.githubusercontent.com/69113478/163991477-fcf964b5-3be0-4634-96a8-26f36afd2808.png)

This error seems to be due to "pattern_type='tile'". How can I fix the error?

```r
flags <- c(
  system.file("img", "flag", "au.png", package = "ggpattern"),
  system.file("img", "flag", "dk.png", package = "ggpattern"),
  system.file("img", "flag", "gb.png", package = "ggpattern"),
  system.file("img", "flag", "gr.png", package = "ggpattern"),
  system.file("img", "flag", "no.png", package = "ggpattern"),
  system.file("img", "flag", "se.png", package = "ggpattern"),
  system.file("img", "flag", "us.png", package = "ggpattern")
)

ggplot(data=data,
    aes(x=cut,y=per,pattern_filename =clarity))+
    geom_col_pattern(width = 2,
        stat="identity",position=position_dodge(),
        fill='white',colour='black',
        pattern='image',pattern_type='tile')+
    theme(legend.position = 'none')+
    scale_pattern_filename_discrete(choices = flags)
```
![image](https://user-images.githubusercontent.com/69113478/163990795-40857eaf-57a9-42ed-a5ca-61d9567bbf80.png)

![image](https://user-images.githubusercontent.com/69113478/163990977-d644d31a-55c8-4545-b389-3c9be30415dc.png)

**Comment by trevorld** [comment] 2022-04-19 17:04
* Your `sessionInfo()` indicates you are using `{ggpattern}` v0.1.3.  Please upgrade to a more recent version of `{ggpattern}` and `{gridpattern}`.  The most recent versions published onto CRAN should be sufficient.
* This appears to be a duplicate of #37 / https://github.com/trevorld/gridpattern/issues/47 which should be fixed if you have `{gridpattern} >= v0.5.3` and a recent version of `{ggpattern}` such as `{ggpattern}` v0.4.2.

**Closed by trevorld** 2022-04-19 17:04 UTC
