### ISSUE TITLE
using without importing the library

### ISSUE THREAD

**Issue by idavydov** [coolbutuseless/ggpattern#50] opened 2021-07-26 11:45 UTC
Is there a way to use this library without calling `library(ggpattern)`?

I get the following error:

``` r
df <- data.frame(level = c("a", "b", "c", 'd'), outcome = c(2.3, 1.9, 3.2, 1))

ggplot2::ggplot(df) +
  ggplot2::aes(level, outcome, pattern_fill = level) +
  ggpattern::geom_col_pattern() 
#> Loading required namespace: memoise
#> Error in grDevices::col2rgb(colour, alpha = TRUE): invalid color name 'a'
```

<sup>Created on 2021-07-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Works fine if I add `library(ggpattern)` at the very top.

P.S. Great library by the way, thank you.

**Comment by trevorld** [comment] 2021-07-26 13:59
This is a duplicate of #40 .  Explicitly set your `pattern_fill` values or explicitly add in a ``ggpattern::scale_pattern_fill_discrete()`` (which `{ggplot2}` can't find if it isn't visible to it).

**Closed by trevorld** 2021-07-26 13:59 UTC

**Comment by idavydov** [comment] 2021-07-27 07:45
Great, thank you very much.
